# Generated by Django 5.1 on 2024-10-20 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='template',
            name='idempresa',
        ),
        migrations.AddField(
            model_name='foto',
            name='caminho',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='foto',
            name='metadados',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='TemplateRelatorio',
            fields=[
                ('idtemplate_relatorio', models.AutoField(primary_key=True, serialize=False)),
                ('pedidos_fotos', models.JSONField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.administrador')),
                ('idempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioFinal',
            fields=[
                ('idrelatorio_final', models.AutoField(primary_key=True, serialize=False)),
                ('endereco_server', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('data_visita', models.DateField()),
                ('fotos', models.ManyToManyField(to='reporter.foto')),
                ('idsitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.sitio')),
                ('tecnico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.tecnico')),
                ('idtemplate_relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.templaterelatorio')),
            ],
        ),
        migrations.DeleteModel(
            name='relatorio_final',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
