# Generated by Django 5.1 on 2024-10-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_remove_template_administrator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
