# Generated by Django 5.1 on 2024-10-21 00:57

import django.utils.timezone
import reporter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_alter_administrador_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriofinal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatoriofinal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='relatoriofinal',
            name='endereco_server',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='templaterelatorio',
            name='pedidos_fotos',
            field=models.JSONField(default=reporter.models.default_pedidos_fotos, help_text='Especifique as fotos que precisam ser solicitadas para este relatório em formato JSON.'),
        ),
    ]
