# Generated by Django 5.1 on 2024-10-21 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_relatoriofinal_created_at_relatoriofinal_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriofinal',
            name='fotos',
        ),
    ]
