# Generated by Django 5.1 on 2024-10-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_remove_relatoriofinal_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriofinal',
            name='fotos',
            field=models.ManyToManyField(to='reporter.foto'),
        ),
    ]
