# Generated by Django 5.1 on 2024-10-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_relatoriofinal_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriofinal',
            name='endereco_server',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
