# Generated by Django 5.1 on 2024-11-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_alter_relatoriofinal_endereco_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='nome',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
